# Generated by Django 4.2 on 2024-11-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rutaCritica", "0001_initial"),
        ("ubicacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, unique=True, verbose_name="Código"),
                ),
                (
                    "recording_Start",
                    models.DateTimeField(verbose_name="Recording Start"),
                ),
                ("recording_End", models.DateTimeField(verbose_name="Recording End")),
                ("estado", models.CharField(max_length=16, verbose_name="Estado")),
                (
                    "rutaCritica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rutaCritica.rutacritica",
                        verbose_name="Ruta Crítica",
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ubicacion.ubicacion",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cámaras",
            },
        ),
    ]
