# Generated by Django 4.2 on 2024-11-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("especie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=3, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="especie.especie",
                        verbose_name="Especie",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Animales",
            },
        ),
    ]
