# Generated by Django 4.2 on 2024-11-09 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tipoDenuncia", "0001_initial"),
        ("rutaCritica", "0001_initial"),
        ("animal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, unique=True, verbose_name="Código"),
                ),
                (
                    "descripcion_persona",
                    models.CharField(
                        max_length=1000,
                        verbose_name="Descripción de persona involucrada",
                    ),
                ),
                (
                    "descripcion_hechos",
                    models.CharField(
                        max_length=1000, verbose_name="Descripción de los hechos"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=1000, verbose_name="Dirección"),
                ),
                ("zona", models.CharField(max_length=8, verbose_name="Zona")),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "rutaCritica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rutaCritica.rutacritica",
                        verbose_name="Ruta Crítica",
                    ),
                ),
                (
                    "tipoDenuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tipoDenuncia.tipodenuncia",
                        verbose_name="Tipo de Denuncia",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Denuncias",
            },
        ),
        migrations.CreateModel(
            name="DetalleDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=5, unique=True, verbose_name="Código"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="animal.animal",
                        verbose_name="Animal",
                    ),
                ),
                (
                    "denuncia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Denuncia.denuncia",
                        verbose_name="Denuncia",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Detalles de Denuncia",
            },
        ),
    ]
