# Generated by Django 4.2 on 2024-11-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledenuncia',
            name='denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='Denuncia.denuncia', verbose_name='Denuncia'),
        ),
    ]
